### ISSUE TITLE
Adjust hover styles in mobile resolutions

### ISSUE THREAD

**Issue by devsarmico** [devsarmico/react-playlist-player#6]
The player icons are getting bigger when touched.

Since there is no hover in mobile devices these effects should only be applied in desktop resolutions (> 1280px)

**Comment by devsarmico** [comment]
@hitunes Can you explain what you did in the pull request related to this issue?

I've already merged it but for tracking/history sake it'll be nice if you explain your solution here so that I can close this issue confidently :)

**Comment by hitunes** [comment]
i made the hover work alone on screen greater than 1280px with media query
